spring:
  profiles: dev
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planit_account?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: planit
    password: planit1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    hibernate:
      ddl-auto: create